[build]
command = "npm run build:prod"
publish = "dist/car-kaashiv-angular/browser"

[context.branch-deploy]
command = "npm run build:staging"

[[redirects]]
from = "/api/*"
to = "https://carkaashiv-angular-api.onrender.com/api/:splat"
status = 200
force = true

[[context.branch-deploy.redirects]]
from = "/api/*"
to = "https://carkaashiv-api-staging.onrender.com/api/:splat"
status = 200
force = true